"""
Centralized command ID normalization table.
Used by both the command drop handler and the preview command store
to ensure consistent cid strings throughout the replay system.
"""

COMMAND_ID_ALIASES: dict[str, str] = {
    # geometry
    "flip_horizontal": "geom_flip_horizontal",
    "geom_flip_h": "geom_flip_horizontal",
    "geom_flip_horizontal": "geom_flip_horizontal",
    "flip_vertical": "geom_flip_vertical",
    "geom_flip_v": "geom_flip_vertical",
    "geom_rotate_clockwise": "geom_rotate_clockwise",
    "rotate_clockwise": "geom_rotate_clockwise",
    "geom_rot_cw": "geom_rotate_clockwise",
    "rotate_counterclockwise": "geom_rotate_counterclockwise",
    "geom_rot_ccw": "geom_rotate_counterclockwise",
    "geom_rotate_counterclockwise": "geom_rotate_counterclockwise",
    "rotate_180": "geom_rotate_180",
    "geom_rotate_180": "geom_rotate_180",
    "rotate_any": "geom_rotate_any",
    "rotate_arbitrary": "geom_rotate_any",
    "geom_rotate_any": "geom_rotate_any",
    "invert": "geom_invert",
    "geom_invert": "geom_invert",
    "rescale": "geom_rescale",
    "geom_rescale": "geom_rescale",
    "geom_resize_canvas": "geom_resize_canvas",
    "resize_canvas": "geom_resize_canvas",
    # stretch / tone
    "stat_stretch": "stat_stretch",
    "statistical_stretch": "stat_stretch",
    "statistical stretch": "stat_stretch",
    "star_stretch": "star_stretch",
    "star stretch": "star_stretch",
    "levels": "levels",
    "histogram_transform": "levels",
    "histogram": "levels",
    "ghs": "ghs",
    "hyperbolic_stretch": "ghs",
    "universal_hyperbolic_stretch": "ghs",
    "curves": "curves",
    "pedestal": "pedestal",
    "linear_fit": "linear_fit",
    "linear fit": "linear_fit",
    # background / color
    "abe": "abe",
    "automatic_background_extraction": "abe",
    "graxpert": "graxpert",
    "grax": "graxpert",
    "remove_gradient_graxpert": "graxpert",
    "background_neutral": "background_neutral",
    "background neutralization": "background_neutral",
    "white_balance": "white_balance",
    "white balance": "white_balance",
    "remove_green": "remove_green",
    "remove green": "remove_green",
    # stars
    "remove_stars": "remove_stars",
    "star_removal": "remove_stars",
    "starnet": "remove_stars",
    "darkstar": "remove_stars",
    # AI tools
    "aberrationai": "aberrationai",
    "aberration": "aberrationai",
    "ai_aberration": "aberrationai",
    "aberration correction (ai)": "aberrationai",
    "cosmic": "cosmic_clarity",
    "cosmicclarity": "cosmic_clarity",
    "cosmic_clarity": "cosmic_clarity",
    "cosmic clarity": "cosmic_clarity",
    "cosmic clarity – denoise": "cosmic_clarity",
    "cosmic clarity – sharpen": "cosmic_clarity",
    "cosmic clarity - denoise": "cosmic_clarity",
    "cosmic clarity - sharpen": "cosmic_clarity",
    "syqontools": "syqontools",
    # processing
    "texture_clarity": "texture_clarity",
    "texture and clarity": "texture_clarity",
    "texture clarity": "texture_clarity",
    "crop": "crop",
    "geom_crop": "crop",
    "wavescale_hdr": "wavescale_hdr",
    "wavescalehdr": "wavescale_hdr",
    "wavescale": "wavescale_hdr",
    "wavescale_dark_enhance": "wavescale_dark_enhance",
    "wavescale_dark_enhancer": "wavescale_dark_enhance",
    "wavescale dark enhancer": "wavescale_dark_enhance",
    "wsde": "wavescale_dark_enhance",
    "dark_enhancer": "wavescale_dark_enhance",
    "clahe": "clahe",
    "morphology": "morphology",
    "pixel_math": "pixel_math",
    "pixel math": "pixel_math",
    "halo_b_gon": "halo_b_gon",
    "halo-b-gon": "halo_b_gon",
    "convo": "convo",
    "convolution": "convo",
    "deconvolution": "convo",
    "convo_deconvo": "convo",
    # alignment / astrometry
    "star_alignment": "star_align",
    "align_stars": "star_align",
    "star align": "star_align",
    "rgb_align": "rgb_align",
    "plate_solve": "plate_solve",
    "debayer": "debayer",
}


def normalize_command_id(cid: str) -> str:
    """Normalize a raw command id or step name to the canonical cid string."""
    return COMMAND_ID_ALIASES.get(str(cid or "").strip().lower(), str(cid or "").strip().lower())